"""add resume_documents table

Revision ID: 5e32a4cf9cd5
Revises: 0b4099b04a31
Create Date: 2026-10-10 09:27:39.980848

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
 

# revision identifiers, used by Alembic.
revision: str = '5e32a4cf9cd5'
down_revision: Union[str, None] = '0b4099b04a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.String(length=20), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_documents_resume_id'), 'resume_documents', ['resume_id'], unique=True)
    op.create_index(op.f('ix_resume_documents_user_id'), 'resume_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_documents_user_id'), table_name='resume_documents')
    op.drop_index(op.f('ix_resume_documents_resume_id'), table_name='resume_documents')
    op.drop_table('resume_documents')
    # ### end Alembic commands ###
